### PR TITLE
cortex m4 support

### PR DESCRIPTION
**Pull request by baloo**
cortex-m4 is using thumbv7em-none-eabi target

### CODE REVIEW

**Comment by baloo** [comment]
note: this also happens to add support for Cortex-M7, Cortex-M4F and Cortex-M7F

**Comment by Nemo157** [comment]
LGTM, I'll get back to trying to fix the build in #25 sometime this week or weekend then merge.

**Comment by baloo** [comment]
sounds good! thanks for your work :)

**Comment by Nemo157** [comment]
bors retry

**Comment by Nemo157** [comment]
bors retry

**Pull request merged**
